name: batch_TO_RL
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.5
  - pip
  - numpy
  - matplotlib
  - pytorch
  - scipy
  - pytest
  - mujoco
  - ipython
  - cvxopt
  - seaborn
  - pip:
      - siren_pytorch
      - pin
      - qpsolvers
      - osqp
      - robot-descriptions
